import { DAYS, FAQS, opts, PUBLISHING, SEO, VERTICALS, WEEKDAYS, type ResourceConfig } from "./fields";

const PUB_COL = { name: "publishing.status", label: "Status", type: "badge" as const };

export const RESOURCES: ResourceConfig[] = [
  /* ───────────── Catalogue ───────────── */
  {
    key: "properties",
    label: "Properties",
    singular: "Property",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "Property",
    titleField: "name",
    publicPath: "/stays/{slug}",
    searchFields: ["name", "slug", "location.area"],
    defaultSort: { sortOrder: 1, name: 1 },
    columns: [
      { name: "featuredImage", label: "", type: "image" },
      { name: "name", label: "Name" },
      { name: "type", label: "Type" },
      { name: "pricing.baseRate", label: "Base / night", type: "money" },
      { name: "status", label: "Operations", type: "badge" },
      PUB_COL,
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, section: "Basics", width: "half" },
      { name: "slug", label: "URL slug", type: "slug", section: "Basics", width: "half", help: "Auto-generated from the name if left empty." },
      { name: "type", label: "Property type", type: "select", required: true, section: "Basics", width: "third", options: opts(["studio", "Studio apartment"], ["1bhk", "1 BHK"], ["2bhk", "2 BHK"], ["3bhk", "3 BHK"], ["4bhk", "4 BHK"], ["villa", "Villa"]) },
      { name: "label", label: "Badge / label", type: "text", section: "Basics", width: "third", help: "Optional short label, e.g. ATT." },
      { name: "featured", label: "Featured on homepage", type: "boolean", section: "Basics", width: "third" },
      { name: "tagline", label: "Tagline", type: "text", section: "Basics", width: "full" },
      { name: "shortDescription", label: "Card description", type: "textarea", section: "Basics", width: "full" },
      { name: "description", label: "Full description", type: "textarea", section: "Basics", width: "full", help: "Blank line = new paragraph." },
      { name: "highlights", label: "Highlights (one per line)", type: "lines", section: "Basics" },
      { name: "collections", label: "Collections / tags", type: "tags", section: "Basics", help: "Used for filters, e.g. Family, Near Prem Mandir." },
      { name: "sortOrder", label: "Sort order", type: "number", section: "Basics", width: "third" },

      { name: "bedrooms", label: "Bedrooms", type: "number", section: "Rooms & guests", width: "third" },
      { name: "bathrooms", label: "Bathrooms", type: "number", section: "Rooms & guests", width: "third" },
      { name: "occupancy.maxGuests", label: "Max guests", type: "number", section: "Rooms & guests", width: "third" },
      { name: "occupancy.baseGuests", label: "Guests included in price", type: "number", section: "Rooms & guests", width: "third" },
      { name: "occupancy.maxAdults", label: "Max adults", type: "number", section: "Rooms & guests", width: "third" },
      { name: "occupancy.maxChildren", label: "Max children", type: "number", section: "Rooms & guests", width: "third" },
      { name: "beds", label: "Where you'll sleep", type: "list", section: "Rooms & guests", fields: [{ name: "room", label: "Room", type: "text" }, { name: "bedType", label: "Beds", type: "text" }] },
      { name: "amenityIds", label: "Amenities", type: "refs", ref: "amenities", section: "Rooms & guests" },
      { name: "houseRules", label: "House rules (one per line)", type: "lines", section: "Rooms & guests" },
      { name: "checkInTime", label: "Check-in time", type: "time", section: "Rooms & guests", width: "half" },
      { name: "checkOutTime", label: "Check-out time", type: "time", section: "Rooms & guests", width: "half" },

      { name: "location.area", label: "Area / locality", type: "text", section: "Location", width: "half" },
      { name: "location.city", label: "City", type: "text", section: "Location", width: "half" },
      { name: "location.mapUrl", label: "Approximate map link", type: "text", section: "Location", width: "full", help: "Public. Link to the area, not the exact door." },
      { name: "location.lat", label: "Latitude (approx.)", type: "number", section: "Location", width: "half" },
      { name: "location.lng", label: "Longitude (approx.)", type: "number", section: "Location", width: "half" },
      { name: "location.exactAddress", label: "Exact address (private)", type: "textarea", section: "Location", width: "full", help: "Never shown publicly; for confirmations." },
      { name: "location.nearby", label: "Nearby", type: "list", section: "Location", fields: [{ name: "name", label: "Place", type: "text" }, { name: "distance", label: "Distance", type: "text" }] },

      { name: "featuredImage", label: "Featured image", type: "image", folder: "properties", section: "Media" },
      { name: "gallery", label: "Gallery (tag each photo with a room)", type: "gallery", folder: "properties", section: "Media", width: "full", groupsFrom: "photoTour" },
      {
        name: "photoTour",
        label: "Photo tour rooms",
        type: "list",
        section: "Media",
        width: "full",
        help: "Rooms in the order shown on the “All photos” page, each with a short amenity line. Untagged photos appear under “Additional photos”.",
        fields: [
          { name: "name", label: "Room name", type: "text", placeholder: "Living room" },
          { name: "highlights", label: "Amenities in this room (one per line)", type: "lines" },
        ],
      },

      { name: "pricing.baseRate", label: "Base nightly rate", type: "money", section: "Pricing", width: "third", required: true },
      { name: "pricing.weekendRate", label: "Weekend nightly rate", type: "money", section: "Pricing", width: "third" },
      { name: "pricing.compareAtRate", label: "Strike-through rate", type: "money", section: "Pricing", width: "third", help: "Shown crossed out if higher." },
      { name: "pricing.weekendDays", label: "Weekend nights", type: "multiselect", options: WEEKDAYS, numeric: true, section: "Pricing", default: [5, 6] },
      { name: "extraGuest.enabled", label: "Charge for extra guests", type: "boolean", section: "Pricing", width: "third" },
      { name: "extraGuest.adultPerNight", label: "Extra adult / night", type: "money", section: "Pricing", width: "third" },
      { name: "extraGuest.childPerNight", label: "Extra child / night", type: "money", section: "Pricing", width: "third" },
      { name: "stayRules.minNights", label: "Minimum nights", type: "number", section: "Pricing", width: "half" },
      { name: "stayRules.maxNights", label: "Maximum nights", type: "number", section: "Pricing", width: "half" },
      { name: "mealPlanIds", label: "Meal plans offered", type: "refs", ref: "meal-plans", section: "Pricing", help: "Empty = all active meal plans." },
      { name: "addOnIds", label: "Add-ons offered", type: "refs", ref: "add-ons", section: "Pricing", help: "Empty = all active stay add-ons." },
      { name: "cancellationPolicyId", label: "Cancellation policy", type: "ref", ref: "policies", section: "Pricing" },

      { name: "status", label: "Operational status", type: "select", section: "Availability & channel", width: "half", options: opts(["active", "Active"], ["maintenance", "Under maintenance"], ["inactive", "Inactive (hidden)"]), default: "active" },
      { name: "maintenanceNote", label: "Maintenance note", type: "text", section: "Availability & channel", width: "half" },
      { name: "pricingSource", label: "Rates come from", type: "select", section: "Availability & channel", options: opts(["local", "Website pricing (this form)"], ["channel", "Channel manager (eZee)"]), default: "local" },
      { name: "channel.externalPropertyId", label: "eZee hotel code", type: "text", section: "Availability & channel", width: "third" },
      { name: "channel.externalRoomTypeId", label: "eZee room type ID", type: "text", section: "Availability & channel", width: "third" },
      { name: "channel.externalRatePlanId", label: "eZee rate plan ID", type: "text", section: "Availability & channel", width: "third" },
      FAQS,
      PUBLISHING,
      ...SEO,
    ],
  },
  {
    key: "tours",
    label: "Darshan Tours",
    singular: "Darshan tour",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "DarshanTour",
    titleField: "title",
    publicPath: "/darshan-tours/{slug}",
    searchFields: ["title", "slug"],
    defaultSort: { sortOrder: 1, nights: 1 },
    columns: [
      { name: "heroImage", label: "", type: "image" },
      { name: "title", label: "Title" },
      { name: "durationLabel", label: "Duration" },
      { name: "pricing.adultPrice", label: "Per person", type: "money" },
      { name: "bookingMode", label: "Booking", type: "badge" },
      PUB_COL,
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, section: "Overview", width: "half" },
      { name: "slug", label: "URL slug", type: "slug", section: "Overview", width: "half" },
      { name: "durationLabel", label: "Duration label", type: "text", section: "Overview", width: "third", placeholder: "2 Nights / 3 Days" },
      { name: "nights", label: "Nights", type: "number", section: "Overview", width: "third" },
      { name: "days", label: "Days", type: "number", section: "Overview", width: "third" },
      { name: "eyebrow", label: "Hero eyebrow", type: "text", section: "Overview", width: "half", placeholder: "From Mathura" },
      { name: "featured", label: "Featured", type: "boolean", section: "Overview", width: "third" },
      { name: "sortOrder", label: "Sort order", type: "number", section: "Overview", width: "third" },
      { name: "subtitle", label: "Hero subtitle", type: "textarea", section: "Overview", width: "full" },
      { name: "overview", label: "Overview", type: "textarea", section: "Overview", width: "full" },
      { name: "highlights", label: "Highlights (one per line)", type: "lines", section: "Overview" },
      { name: "heroImage", label: "Hero image", type: "image", folder: "tours", section: "Media" },
      { name: "gallery", label: "Gallery", type: "gallery", folder: "tours", section: "Media", width: "full" },

      { name: "pricing.adultPrice", label: "Price per person", type: "money", required: true, section: "Pricing & rules", width: "third" },
      { name: "pricing.childPrice", label: "Child price", type: "money", section: "Pricing & rules", width: "third", help: "Empty = adult price." },
      { name: "pricing.childAgeMax", label: "Child up to age", type: "number", section: "Pricing & rules", width: "third" },
      { name: "pricing.compareAtPrice", label: "Strike-through price", type: "money", section: "Pricing & rules", width: "third" },
      { name: "pricing.priceBasisNote", label: "Price note", type: "text", section: "Pricing & rules", width: "full", placeholder: "per person · twin sharing · all-inclusive" },
      { name: "pricing.groupTiers", label: "Group pricing tiers", type: "list", section: "Pricing & rules", fields: [{ name: "minPeople", label: "From people", type: "number" }, { name: "maxPeople", label: "To people", type: "number" }, { name: "adultPrice", label: "Price per person", type: "money" }] },
      { name: "minGroupSize", label: "Minimum group size", type: "number", section: "Pricing & rules", width: "third", default: 4 },
      { name: "maxGroupSize", label: "Maximum group size", type: "number", section: "Pricing & rules", width: "third" },
      { name: "childrenCountTowardMinimum", label: "Children count toward minimum", type: "boolean", section: "Pricing & rules", width: "third", default: true },
      { name: "advanceDays", label: "Book at least (days ahead)", type: "number", section: "Pricing & rules", width: "third", default: 15 },
      { name: "bookingMode", label: "Booking mode", type: "select", section: "Pricing & rules", width: "third", options: opts(["both", "Book online + enquire"], ["online", "Online booking only"], ["enquiry", "Enquiry only"]), default: "both" },
      { name: "dateMode", label: "Dates", type: "select", section: "Pricing & rules", width: "third", options: opts(["any_date", "Any date"], ["fixed_dates", "Fixed departures only"]), default: "any_date" },
      { name: "dailyCapacity", label: "Max people per date", type: "number", section: "Pricing & rules", width: "third", help: "Empty = unlimited." },
      { name: "blackoutDates", label: "Unavailable dates (YYYY-MM-DD)", type: "tags", section: "Pricing & rules" },
      { name: "addOnIds", label: "Add-ons offered", type: "refs", ref: "add-ons", section: "Pricing & rules" },
      { name: "cancellationPolicyId", label: "Cancellation policy", type: "ref", ref: "policies", section: "Pricing & rules" },

      { name: "itinerary", label: "Day-by-day itinerary", type: "list", section: "Itinerary", width: "full", fields: DAYS },

      { name: "stayInfo", label: "Stay information", type: "textarea", section: "Stay, meals & travel", width: "full" },
      { name: "stayPropertyIds", label: "VHI properties used", type: "refs", ref: "properties", section: "Stay, meals & travel" },
      { name: "stayAllocation", label: "Property allocation", type: "select", section: "Stay, meals & travel", options: opts(["manual", "Manual (assign after booking)"], ["auto", "Automatic (hold first available)"]), default: "manual" },
      { name: "mealInfo", label: "Meal information", type: "textarea", section: "Stay, meals & travel", width: "full" },
      { name: "inclusions", label: "What's included (one per line)", type: "lines", section: "Stay, meals & travel" },
      { name: "exclusions", label: "Not included (one per line)", type: "lines", section: "Stay, meals & travel" },
      { name: "pickupInfo", label: "Pickup & drop information", type: "textarea", section: "Stay, meals & travel", width: "full" },
      { name: "pickupPoints", label: "Pickup points (one per line)", type: "lines", section: "Stay, meals & travel" },
      { name: "vehicleInfo", label: "Vehicle information", type: "textarea", section: "Stay, meals & travel", width: "full" },
      { name: "travelFacts", label: "Travel facts", type: "list", section: "Stay, meals & travel", fields: [{ name: "label", label: "Label", type: "text" }, { name: "value", label: "Value", type: "text" }] },
      { name: "importantInfo", label: "Important information (one per line)", type: "lines", section: "Stay, meals & travel" },
      { name: "relatedTourIds", label: "Other Braj journeys", type: "refs", ref: "tours", section: "Stay, meals & travel" },
      FAQS,
      PUBLISHING,
      ...SEO,
    ],
  },
  {
    key: "packages",
    label: "Stay + Food Packages",
    singular: "Stay + Food package",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "StayPackage",
    titleField: "title",
    publicPath: "/stay-food/{slug}",
    defaultSort: { nights: 1 },
    columns: [
      { name: "heroImage", label: "", type: "image" },
      { name: "title", label: "Title" },
      { name: "nights", label: "Nights" },
      { name: "pricingMode", label: "Pricing" },
      PUB_COL,
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, section: "Package", width: "half" },
      { name: "slug", label: "URL slug", type: "slug", section: "Package", width: "half" },
      { name: "nights", label: "Nights", type: "number", required: true, section: "Package", width: "third" },
      { name: "featured", label: "Featured", type: "boolean", section: "Package", width: "third" },
      { name: "sortOrder", label: "Sort order", type: "number", section: "Package", width: "third" },
      { name: "tagline", label: "Tagline", type: "text", section: "Package", width: "full" },
      { name: "description", label: "Description", type: "textarea", section: "Package", width: "full" },
      { name: "heroImage", label: "Hero image", type: "image", folder: "packages", section: "Package" },
      { name: "gallery", label: "Gallery", type: "gallery", folder: "packages", section: "Package", width: "full" },
      { name: "propertyIds", label: "Eligible stays", type: "refs", ref: "properties", section: "Stays, meals & price", help: "Empty = all active stays." },
      { name: "mealPlanIds", label: "Meal plans", type: "refs", ref: "meal-plans", section: "Stays, meals & price" },
      { name: "pricingMode", label: "Pricing mode", type: "select", section: "Stays, meals & price", options: opts(["dynamic", "Stay rate + selected meal plan"], ["fixed_per_package", "Fixed price per package"], ["fixed_per_person", "Fixed price per person"]), default: "dynamic" },
      { name: "price", label: "Fixed price", type: "money", section: "Stays, meals & price", width: "half" },
      { name: "compareAtPrice", label: "Strike-through price", type: "money", section: "Stays, meals & price", width: "half" },
      { name: "offerText", label: "Offer text", type: "text", section: "Stays, meals & price", width: "full" },
      { name: "inclusions", label: "Included services (one per line)", type: "lines", section: "Stays, meals & price" },
      { name: "exclusions", label: "Not included (one per line)", type: "lines", section: "Stays, meals & price" },
      { name: "itineraryId", label: "Itinerary", type: "ref", ref: "itineraries", section: "Itinerary & tips" },
      { name: "localRecommendations", label: "Local food recommendations", type: "list", section: "Itinerary & tips", fields: [{ name: "title", label: "Place / dish", type: "text" }, { name: "description", label: "Why", type: "textarea" }] },
      { name: "cancellationPolicyId", label: "Cancellation policy", type: "ref", ref: "policies", section: "Itinerary & tips" },
      FAQS,
      PUBLISHING,
      ...SEO,
    ],
  },
  {
    key: "itineraries",
    label: "Itineraries",
    singular: "Itinerary",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "Itinerary",
    titleField: "title",
    defaultSort: { nights: 1 },
    columns: [{ name: "title", label: "Title" }, { name: "nights", label: "Nights" }],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, width: "half" },
      { name: "nights", label: "Nights", type: "number", width: "third" },
      { name: "printedCopyIncluded", label: "Printed copy at check-in", type: "boolean", width: "third", default: true },
      { name: "summary", label: "Summary", type: "textarea", width: "full" },
      { name: "pdf", label: "Itinerary PDF", type: "image", folder: "itineraries", help: "Upload the PDF to the media library and pick it here." },
      { name: "days", label: "Days", type: "list", width: "full", fields: DAYS },
    ],
  },
  {
    key: "amenities",
    label: "Amenities",
    singular: "Amenity",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "Amenity",
    titleField: "name",
    defaultSort: { group: 1, sortOrder: 1 },
    columns: [{ name: "name", label: "Name" }, { name: "group", label: "Group" }, { name: "icon", label: "Icon" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half" },
      { name: "group", label: "Group", type: "text", width: "half", placeholder: "Essentials" },
      { name: "icon", label: "Icon (Lucide name)", type: "text", width: "half", help: "e.g. Wifi, Snowflake, CookingPot, Car, Tv, ShieldCheck" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "half" },
    ],
  },
  {
    key: "add-ons",
    label: "Add-ons",
    singular: "Add-on",
    group: "Catalogue",
    permission: "catalog.edit",
    model: "AddOn",
    titleField: "name",
    defaultSort: { sortOrder: 1 },
    columns: [{ name: "name", label: "Name" }, { name: "category", label: "Category" }, { name: "price", label: "Price", type: "money" }, { name: "pricingUnit", label: "Unit" }, { name: "active", label: "Active", type: "boolean" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half" },
      { name: "code", label: "Code", type: "text", required: true, width: "half", placeholder: "PICKUP" },
      { name: "category", label: "Category", type: "select", width: "third", options: opts(["pickup", "Pick-up"], ["drop", "Drop"], ["scooty", "Scooty rental"], ["cab", "Cab"], ["special", "Special request"], ["other", "Other"]) },
      { name: "pricingUnit", label: "Priced", type: "select", width: "third", options: opts(["per_trip", "Per trip"], ["per_day", "Per day"], ["per_person", "Per person"], ["per_booking", "Per booking"], ["on_request", "On request (₹0 at checkout)"]) },
      { name: "price", label: "Price", type: "money", width: "third" },
      { name: "maxQty", label: "Max quantity", type: "number", width: "third" },
      { name: "icon", label: "Icon (Lucide name)", type: "text", width: "third", placeholder: "Car" },
      { name: "active", label: "Active", type: "boolean", width: "third", default: true },
      { name: "appliesTo", label: "Available for", type: "multiselect", options: VERTICALS, default: ["stay", "stay_food", "darshan"] },
      { name: "description", label: "Description", type: "textarea", width: "full" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "third" },
    ],
  },

  /* ───────────── Pricing & offers ───────────── */
  {
    key: "meal-plans",
    label: "Meal Plans",
    singular: "Meal plan",
    group: "Pricing & offers",
    permission: "pricing.edit",
    model: "MealPlan",
    titleField: "name",
    defaultSort: { sortOrder: 1 },
    columns: [{ name: "name", label: "Name" }, { name: "adultPrice", label: "Adult", type: "money" }, { name: "childPrice", label: "Child", type: "money" }, { name: "minNights", label: "Min nights" }, { name: "active", label: "Active", type: "boolean" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half", placeholder: "Breakfast + Dinner" },
      { name: "code", label: "Code", type: "text", required: true, width: "half", placeholder: "BFD" },
      { name: "pricingModel", label: "Pricing model", type: "select", width: "half", options: opts(["per_person_per_night", "Per person, per night"], ["per_booking_per_night", "Per booking, per night"]), default: "per_person_per_night" },
      { name: "active", label: "Active", type: "boolean", width: "half", default: true },
      { name: "adultPrice", label: "Adult price", type: "money", width: "third", required: true },
      { name: "childPrice", label: "Child price", type: "money", width: "third" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "third" },
      { name: "childAgeMin", label: "Children free below age", type: "number", width: "half", default: 5 },
      { name: "childAgeMax", label: "Child price up to age", type: "number", width: "half", default: 11 },
      { name: "minNights", label: "Available from (nights)", type: "number", width: "half", default: 3, help: "Eligibility rule for this meal plan." },
      { name: "nightsRule", label: "Rule", type: "select", width: "half", options: opts(["gte", "…nights or more"], ["gt", "More than … nights"]), default: "gte" },
      { name: "description", label: "Description", type: "textarea", width: "full" },
      { name: "servingInfo", label: "Serving information", type: "textarea", width: "full" },
      { name: "timings", label: "Timings", type: "text", width: "full" },
      { name: "image", label: "Image", type: "image", folder: "packages" },
    ],
  },
  {
    key: "price-rules",
    label: "Seasonal Pricing",
    singular: "Price rule",
    group: "Pricing & offers",
    permission: "pricing.edit",
    model: "PriceRule",
    titleField: "name",
    defaultSort: { from: -1 },
    description: "Festival, season and single-date rates. Order: base → weekend → highest-priority season/festival → date override.",
    columns: [{ name: "name", label: "Name" }, { name: "kind", label: "Kind", type: "badge" }, { name: "from", label: "From" }, { name: "to", label: "To" }, { name: "active", label: "Active", type: "boolean" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half", placeholder: "Holi 2027" },
      { name: "kind", label: "Kind", type: "select", required: true, width: "half", options: opts(["festival", "Festival"], ["season", "Season"], ["date_override", "Date override"]) },
      { name: "from", label: "From", type: "date", required: true, width: "half" },
      { name: "to", label: "To (inclusive)", type: "date", required: true, width: "half" },
      { name: "adjustmentType", label: "Adjustment", type: "select", required: true, width: "half", options: opts(["percent", "Percent change (+/−)"], ["fixed_rate", "Fixed nightly rate"], ["flat_delta", "Flat change per night"]) },
      { name: "adjustmentValue", label: "Value", type: "number", required: true, width: "half", help: "Percent (e.g. 40), or paise for fixed/flat (₹5,000 = 500000)." },
      { name: "appliesToAll", label: "Applies to all properties", type: "boolean", width: "half", default: true },
      { name: "priority", label: "Priority", type: "number", width: "half" },
      { name: "propertyIds", label: "Only these properties", type: "refs", ref: "properties" },
      { name: "active", label: "Active", type: "boolean", default: true },
    ],
  },
  {
    key: "blocks",
    label: "Availability Blocks",
    singular: "Availability block",
    group: "Pricing & offers",
    permission: "pricing.edit",
    model: "ManualBlock",
    titleField: "note",
    defaultSort: { from: -1 },
    description: "Close dates on the website. Until eZee is connected, mirror Airbnb/OTA bookings here.",
    columns: [{ name: "propertyId", label: "Property" }, { name: "from", label: "From" }, { name: "to", label: "To" }, { name: "reason", label: "Reason", type: "badge" }, { name: "note", label: "Note" }],
    fields: [
      { name: "propertyId", label: "Property", type: "ref", ref: "properties", required: true },
      { name: "from", label: "First night", type: "date", required: true, width: "half" },
      { name: "to", label: "Last night", type: "date", required: true, width: "half" },
      { name: "reason", label: "Reason", type: "select", width: "half", options: opts(["ota", "OTA booking (Airbnb etc.)"], ["owner", "Owner use"], ["maintenance", "Maintenance"], ["other", "Other"]) },
      { name: "note", label: "Note", type: "text", width: "half" },
    ],
  },
  {
    key: "departures",
    label: "Tour Departures",
    singular: "Tour departure",
    group: "Pricing & offers",
    permission: "pricing.edit",
    model: "TourDeparture",
    titleField: "date",
    defaultSort: { date: 1 },
    description: "Capacity and price per date. Created automatically when guests book; add fixed departures here.",
    columns: [{ name: "tourId", label: "Tour" }, { name: "date", label: "Date" }, { name: "capacity", label: "Capacity" }, { name: "booked", label: "Booked" }, { name: "status", label: "Status", type: "badge" }],
    fields: [
      { name: "tourId", label: "Tour", type: "ref", ref: "tours", required: true },
      { name: "date", label: "Date", type: "date", required: true, width: "third" },
      { name: "capacity", label: "Capacity (people)", type: "number", required: true, width: "third" },
      { name: "status", label: "Status", type: "select", width: "third", options: opts("open", "closed", "sold_out"), default: "open" },
      { name: "priceOverride", label: "Price per person override", type: "money", width: "half" },
      { name: "booked", label: "Booked", type: "readonly", width: "half" },
    ],
  },
  {
    key: "offers",
    label: "Offers",
    singular: "Offer",
    group: "Pricing & offers",
    permission: "offers.edit",
    model: "Offer",
    titleField: "name",
    defaultSort: { priority: -1 },
    description: "Automatically applied discounts (best offer wins; coupons replace offers).",
    columns: [{ name: "name", label: "Name" }, { name: "type", label: "Type" }, { name: "value", label: "Value" }, { name: "endsAt", label: "Ends" }, { name: "active", label: "Active", type: "boolean" }],
    fields: [
      { name: "name", label: "Internal name", type: "text", required: true, width: "half" },
      { name: "title", label: "Headline", type: "text", width: "half", placeholder: "Stay 5 nights, save 10%" },
      { name: "description", label: "Description", type: "textarea", width: "full" },
      { name: "badgeText", label: "Badge", type: "text", width: "third", placeholder: "Save 10%" },
      { name: "type", label: "Discount type", type: "select", required: true, width: "third", options: opts(["percent", "Percent"], ["flat", "Flat amount (paise)"]) },
      { name: "value", label: "Value", type: "number", required: true, width: "third", help: "Percent, or paise for flat (₹500 = 50000)." },
      { name: "maxDiscount", label: "Max discount", type: "money", width: "third" },
      { name: "minAmount", label: "Min booking value", type: "money", width: "third" },
      { name: "minNights", label: "Min nights", type: "number", width: "third" },
      { name: "startsAt", label: "Starts", type: "date", width: "half" },
      { name: "endsAt", label: "Ends", type: "date", width: "half" },
      { name: "verticals", label: "Applies to", type: "multiselect", options: VERTICALS, default: ["stay", "stay_food", "darshan"] },
      { name: "propertyIds", label: "Only these stays", type: "refs", ref: "properties" },
      { name: "tourIds", label: "Only these tours", type: "refs", ref: "tours" },
      { name: "packageIds", label: "Only these packages", type: "refs", ref: "packages" },
      { name: "firstBookingOnly", label: "First booking only", type: "boolean", width: "third" },
      { name: "appliesToAddOns", label: "Discount add-ons too", type: "boolean", width: "third" },
      { name: "showStrikeThrough", label: "Show strike-through price", type: "boolean", width: "third", default: true },
      { name: "showOnHomepage", label: "Show on homepage", type: "boolean", width: "third", default: true },
      { name: "priority", label: "Priority", type: "number", width: "third" },
      { name: "active", label: "Active", type: "boolean", width: "third", default: true },
      { name: "image", label: "Image", type: "image", folder: "banners" },
    ],
  },
  {
    key: "coupons",
    label: "Coupons",
    singular: "Coupon",
    group: "Pricing & offers",
    permission: "offers.edit",
    model: "Coupon",
    titleField: "code",
    searchFields: ["code", "name"],
    defaultSort: { createdAt: -1 },
    columns: [{ name: "code", label: "Code" }, { name: "name", label: "Name" }, { name: "value", label: "Value" }, { name: "usedCount", label: "Used" }, { name: "active", label: "Active", type: "boolean" }],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, width: "half", placeholder: "RADHE10" },
      { name: "name", label: "Name", type: "text", required: true, width: "half" },
      { name: "type", label: "Discount type", type: "select", required: true, width: "third", options: opts(["percent", "Percent"], ["flat", "Flat amount (paise)"]) },
      { name: "value", label: "Value", type: "number", required: true, width: "third" },
      { name: "maxDiscount", label: "Max discount", type: "money", width: "third" },
      { name: "minAmount", label: "Min booking value", type: "money", width: "third" },
      { name: "minNights", label: "Min nights", type: "number", width: "third" },
      { name: "usageLimit", label: "Total uses", type: "number", width: "third" },
      { name: "perCustomerLimit", label: "Uses per guest", type: "number", width: "third", default: 1 },
      { name: "usedCount", label: "Used so far", type: "readonly", width: "third" },
      { name: "startsAt", label: "Starts", type: "date", width: "half" },
      { name: "endsAt", label: "Ends", type: "date", width: "half" },
      { name: "verticals", label: "Applies to", type: "multiselect", options: VERTICALS, default: ["stay", "stay_food", "darshan"] },
      { name: "propertyIds", label: "Only these stays", type: "refs", ref: "properties" },
      { name: "tourIds", label: "Only these tours", type: "refs", ref: "tours" },
      { name: "firstBookingOnly", label: "First booking only", type: "boolean", width: "third" },
      { name: "appliesToAddOns", label: "Discount add-ons too", type: "boolean", width: "third" },
      { name: "active", label: "Active", type: "boolean", width: "third", default: true },
    ],
  },
  {
    key: "policies",
    label: "Cancellation Policies",
    singular: "Cancellation policy",
    group: "Pricing & offers",
    permission: "policies.edit",
    model: "CancellationPolicy",
    titleField: "name",
    columns: [{ name: "name", label: "Name" }, { name: "vertical", label: "Offering", type: "badge" }, { name: "isDefault", label: "Default", type: "boolean" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half" },
      { name: "vertical", label: "Offering", type: "select", required: true, width: "third", options: VERTICALS },
      { name: "isDefault", label: "Default for offering", type: "boolean", width: "third" },
      { name: "summary", label: "Short summary (shown at checkout)", type: "text", width: "full" },
      { name: "body", label: "Full policy wording", type: "textarea", width: "full" },
      { name: "rules", label: "Refund tiers", type: "list", help: "Refund % by days before check-in / travel date.", fields: [{ name: "daysBeforeMin", label: "At least N days before", type: "number" }, { name: "refundPercent", label: "Refund %", type: "number" }] },
      { name: "nonRefundableLineTypes", label: "Never refunded", type: "multiselect", options: opts(["addon", "Add-ons"], ["meal", "Meals"], ["extra_guest", "Extra guest charges"]) },
      { name: "fixedDeduction", label: "Processing deduction", type: "money", width: "half" },
      { name: "refundGst", label: "Refund GST on refundable lines", type: "boolean", width: "half", default: true },
    ],
  },

  /* ───────────── Content ───────────── */
  {
    key: "banners",
    label: "Banners",
    singular: "Banner",
    group: "Content",
    permission: "content.edit",
    model: "Banner",
    titleField: "title",
    defaultSort: { placement: 1, sortOrder: 1 },
    description: "Homepage slider: every published banner with placement “Homepage slider” becomes a slide, ordered by Sort order. Slides auto-advance every 6 seconds.",
    columns: [{ name: "image", label: "", type: "image" }, { name: "title", label: "Title" }, { name: "placement", label: "Placement", type: "badge" }, { name: "sortOrder", label: "Order" }, PUB_COL],
    fields: [
      { name: "title", label: "Headline", type: "text", required: true, width: "half", placeholder: "Vrindavan," },
      { name: "titleAccent", label: "Headline, italic line", type: "text", width: "half", placeholder: "as it's meant to be experienced." },
      { name: "placement", label: "Placement", type: "select", width: "third", options: opts(["home_hero", "Homepage slider"], ["stays", "Stays page"], ["darshan", "Darshan page"], ["stay_food", "Stay + Food page"]), default: "home_hero" },
      { name: "textTone", label: "Text colour", type: "select", width: "third", options: opts(["dark", "Dark text (light photo)"], ["light", "White text (dark photo)"]), default: "dark", help: "Pick to match the photo so the headline stays readable." },
      { name: "eyebrow", label: "Eyebrow", type: "text", width: "third", placeholder: "Luxury homestays in Vrindavan" },
      { name: "subtitle", label: "Subtitle", type: "textarea", width: "full" },
      { name: "image", label: "Image (landscape, 2400×1200+, subject on the right)", type: "image", folder: "banners" },
      { name: "mobileImage", label: "Mobile image (portrait, optional)", type: "image", folder: "banners" },
      { name: "video", label: "Background video (optional)", type: "image", folder: "banners" },
      { name: "ctaLabel", label: "Button label", type: "text", width: "half" },
      { name: "ctaHref", label: "Button link", type: "text", width: "half" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "half" },
      { ...PUBLISHING, section: undefined, default: "published" },
    ],
  },
  {
    key: "experiences",
    label: "Vrindavan Experiences",
    singular: "Experience",
    group: "Content",
    permission: "content.edit",
    model: "Experience",
    titleField: "title",
    defaultSort: { sortOrder: 1 },
    columns: [{ name: "image", label: "", type: "image" }, { name: "title", label: "Title" }, { name: "category", label: "Category" }, PUB_COL],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, width: "half" },
      { name: "category", label: "Category", type: "text", width: "half", placeholder: "Temple · Ghat · Parikrama" },
      { name: "description", label: "Description", type: "textarea", width: "full" },
      { name: "bestTime", label: "Best time", type: "text", width: "half" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "half" },
      { name: "image", label: "Image", type: "image", folder: "experiences" },
      { ...PUBLISHING, section: undefined, default: "published" },
    ],
  },
  {
    key: "testimonials",
    label: "Testimonials",
    singular: "Testimonial",
    group: "Content",
    permission: "content.edit",
    model: "Testimonial",
    titleField: "guestName",
    defaultSort: { sortOrder: 1 },
    columns: [{ name: "guestName", label: "Guest" }, { name: "rating", label: "Rating" }, { name: "vertical", label: "About", type: "badge" }, PUB_COL],
    fields: [
      { name: "guestName", label: "Guest name", type: "text", required: true, width: "half" },
      { name: "city", label: "City", type: "text", width: "half" },
      { name: "rating", label: "Rating (1–5)", type: "number", width: "third", default: 5 },
      { name: "stayedIn", label: "When", type: "text", width: "third", placeholder: "March 2026" },
      { name: "vertical", label: "About", type: "select", width: "third", options: opts(["general", "General"], ["stay", "Stay"], ["stay_food", "Stay + Food"], ["darshan", "Darshan"]) },
      { name: "text", label: "Review", type: "textarea", required: true, width: "full" },
      { name: "propertyId", label: "Property", type: "ref", ref: "properties" },
      { name: "tourId", label: "Tour", type: "ref", ref: "tours" },
      { name: "image", label: "Guest photo", type: "image", folder: "testimonials" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "half" },
      { ...PUBLISHING, section: undefined, default: "published" },
    ],
  },
  {
    key: "faqs",
    label: "FAQs",
    singular: "FAQ",
    group: "Content",
    permission: "content.edit",
    model: "Faq",
    titleField: "question",
    defaultSort: { category: 1, sortOrder: 1 },
    columns: [{ name: "question", label: "Question" }, { name: "category", label: "Category", type: "badge" }, { name: "showOnHomepage", label: "Homepage", type: "boolean" }, PUB_COL],
    fields: [
      { name: "question", label: "Question", type: "text", required: true, width: "full" },
      { name: "answer", label: "Answer", type: "textarea", required: true, width: "full" },
      { name: "category", label: "Category", type: "select", width: "third", options: opts(["general", "General"], ["stay", "Stays"], ["stay_food", "Stay + Food"], ["darshan", "Darshan"], ["payments", "Payments"]) },
      { name: "showOnHomepage", label: "Show on homepage", type: "boolean", width: "third" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "third" },
      { ...PUBLISHING, section: undefined, default: "published" },
    ],
  },
  {
    key: "reels",
    label: "Instagram Reels",
    singular: "Reel",
    group: "Content",
    permission: "content.edit",
    model: "Reel",
    titleField: "title",
    defaultSort: { sortOrder: 1 },
    columns: [{ name: "thumbnail", label: "", type: "image" }, { name: "title", label: "Title" }, { name: "label", label: "Label" }, PUB_COL],
    fields: [
      { name: "title", label: "Title", type: "text", width: "half" },
      { name: "label", label: "Label", type: "text", width: "half" },
      { name: "instagramUrl", label: "Instagram URL", type: "text", width: "full" },
      { name: "thumbnail", label: "Thumbnail", type: "image", folder: "reels" },
      { name: "video", label: "Video (Cloudinary)", type: "image", folder: "reels" },
      { name: "sortOrder", label: "Sort order", type: "number", width: "half" },
      { ...PUBLISHING, section: undefined, default: "published" },
    ],
  },
  {
    key: "pages",
    label: "Pages",
    singular: "Page",
    group: "Content",
    permission: "content.edit",
    model: "Page",
    titleField: "title",
    columns: [{ name: "title", label: "Title" }, { name: "slug", label: "Slug" }, PUB_COL],
    description: "About, Privacy Policy, Terms. Body: blank line = paragraph, lines starting with ## = headings.",
    fields: [
      { name: "title", label: "Title", type: "text", required: true, width: "half" },
      { name: "slug", label: "Slug", type: "slug", required: true, width: "half", help: "about · privacy-policy · terms" },
      { name: "intro", label: "Intro", type: "textarea", width: "full" },
      { name: "body", label: "Body", type: "textarea", width: "full" },
      { name: "heroImage", label: "Hero image", type: "image", folder: "pages" },
      { ...PUBLISHING, default: "published" },
      ...SEO,
    ],
  },

  /* ───────────── Operations ───────────── */
  {
    key: "enquiries",
    label: "Enquiries",
    singular: "Enquiry",
    group: "Operations",
    permission: "enquiries.manage",
    model: "Enquiry",
    titleField: "name",
    canCreate: false,
    searchFields: ["name", "phone", "email"],
    defaultSort: { createdAt: -1 },
    columns: [{ name: "createdAt", label: "Received", type: "datetime" }, { name: "name", label: "Name" }, { name: "phone", label: "Phone" }, { name: "subject", label: "About" }, { name: "status", label: "Status", type: "badge" }],
    fields: [
      { name: "name", label: "Name", type: "readonly", width: "half" },
      { name: "phone", label: "Phone", type: "readonly", width: "half" },
      { name: "email", label: "Email", type: "readonly", width: "half" },
      { name: "subject", label: "About", type: "readonly", width: "half" },
      { name: "travelDate", label: "Travel date", type: "readonly", width: "half" },
      { name: "people", label: "People", type: "readonly", width: "half" },
      { name: "message", label: "Message", type: "readonly", width: "full" },
      { name: "status", label: "Status", type: "select", width: "half", options: opts("new", "contacted", "converted", "closed") },
      { name: "notes", label: "Internal notes", type: "textarea", width: "full" },
    ],
  },
  {
    key: "customers",
    label: "Customers",
    singular: "Customer",
    group: "Operations",
    permission: "customers.view",
    model: "Customer",
    titleField: "name",
    canCreate: false,
    canDelete: false,
    searchFields: ["name", "phone", "email"],
    defaultSort: { lastBookingAt: -1 },
    columns: [{ name: "name", label: "Name" }, { name: "phone", label: "Phone" }, { name: "bookingsCount", label: "Bookings" }, { name: "totalSpent", label: "Spent", type: "money" }, { name: "lastBookingAt", label: "Last booking", type: "date" }],
    fields: [
      { name: "name", label: "Name", type: "text", width: "half" },
      { name: "phone", label: "Phone", type: "readonly", width: "half" },
      { name: "email", label: "Email", type: "text", width: "half" },
      { name: "city", label: "City", type: "text", width: "half" },
      { name: "bookingsCount", label: "Bookings", type: "readonly", width: "third" },
      { name: "totalSpent", label: "Total spent (paise)", type: "readonly", width: "third" },
      { name: "notes", label: "Notes", type: "textarea", width: "full" },
    ],
  },

  /* ───────────── Admin ───────────── */
  {
    key: "users",
    label: "Users & Roles",
    singular: "User",
    group: "Admin",
    permission: "users.manage",
    model: "User",
    titleField: "name",
    columns: [{ name: "name", label: "Name" }, { name: "email", label: "Email" }, { name: "role", label: "Role", type: "badge" }, { name: "active", label: "Active", type: "boolean" }, { name: "lastLoginAt", label: "Last login", type: "datetime" }],
    description: "Owner: everything · Manager: operations, pricing, content, analytics · Staff: bookings & enquiries · Editor: content & media.",
    fields: [
      { name: "name", label: "Name", type: "text", required: true, width: "half" },
      { name: "email", label: "Email", type: "text", required: true, width: "half" },
      { name: "role", label: "Role", type: "select", required: true, width: "half", options: opts(["owner", "Owner"], ["manager", "Manager"], ["staff", "Staff"], ["editor", "Content editor"]), default: "staff" },
      { name: "active", label: "Active", type: "boolean", width: "half", default: true },
      { name: "password", label: "Password", type: "password", width: "half", help: "Min. 10 characters. Leave empty to keep the current password." },
    ],
  },
];

export const SETTINGS_RESOURCE: ResourceConfig = {
  key: "settings",
  label: "Settings",
  singular: "Settings",
  group: "Admin",
  permission: "settings.manage",
  model: "Settings",
  titleField: "business.brandName",
  columns: [],
  fields: [
    { name: "business.brandName", label: "Brand name", type: "text", section: "Business", width: "half" },
    { name: "business.tagline", label: "Tagline", type: "text", section: "Business", width: "half" },
    { name: "business.legalName", label: "Legal entity name", type: "text", section: "Business", width: "half" },
    { name: "business.gstin", label: "GSTIN", type: "text", section: "Business", width: "half" },
    { name: "business.registeredAddress", label: "Registered address", type: "textarea", section: "Business", width: "half" },
    { name: "business.invoiceAddress", label: "Invoice address", type: "textarea", section: "Business", width: "half" },
    { name: "business.phone", label: "Helpline (display)", type: "text", section: "Business", width: "third", placeholder: "+91 98xxxxxxx" },
    { name: "business.whatsapp", label: "WhatsApp number", type: "text", section: "Business", width: "third" },
    { name: "business.email", label: "Company email", type: "text", section: "Business", width: "third" },
    { name: "business.address", label: "Public address / area", type: "textarea", section: "Business", width: "half" },
    { name: "business.mapUrl", label: "Map link", type: "text", section: "Business", width: "half" },
    { name: "business.instagram", label: "Instagram", type: "text", section: "Business", width: "third" },
    { name: "business.facebook", label: "Facebook", type: "text", section: "Business", width: "third" },
    { name: "business.youtube", label: "YouTube", type: "text", section: "Business", width: "third" },

    { name: "home.heroEyebrow", label: "Hero eyebrow", type: "text", section: "Homepage", width: "half" },
    { name: "home.heroTitle", label: "Hero headline", type: "text", section: "Homepage", width: "half" },
    { name: "home.heroAccent", label: "Hero accent (italic)", type: "text", section: "Homepage", width: "half" },
    { name: "home.heroSubtitle", label: "Hero subtitle", type: "textarea", section: "Homepage", width: "half" },
    { name: "home.heroImage", label: "Hero image (used if no banner)", type: "image", folder: "banners", section: "Homepage" },
    { name: "home.introTitle", label: "Vrindavan section title", type: "text", section: "Homepage", width: "full" },
    { name: "home.introBody", label: "Vrindavan section text", type: "textarea", section: "Homepage", width: "full" },
    { name: "home.introImage", label: "Vrindavan section image", type: "image", folder: "banners", section: "Homepage" },
    { name: "home.foodTitle", label: "Sattvik food title", type: "text", section: "Homepage", width: "full" },
    { name: "home.foodBody", label: "Sattvik food text", type: "textarea", section: "Homepage", width: "full" },
    { name: "home.foodImage", label: "Sattvik food image", type: "image", folder: "packages", section: "Homepage" },
    { name: "home.whyVhi", label: "Why VHI", type: "list", section: "Homepage", fields: [{ name: "title", label: "Title", type: "text" }, { name: "body", label: "Text", type: "textarea" }] },

    { name: "tax.accommodationRate", label: "GST % — accommodation", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.accommodationSlabLimit", label: "Slab: nightly tariff up to", type: "money", section: "Tax (confirm with your CA)", width: "third", help: "Optional. Lower rate applies up to this tariff." },
    { name: "tax.accommodationRateAboveSlab", label: "GST % above slab", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.stayFoodRate", label: "GST % — Stay + Food packages", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.darshanRate", label: "GST % — Darshan tours", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.mealRate", label: "GST % — meals", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.addonRate", label: "GST % — add-ons", type: "number", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.showPricesWithTax", label: "Show prices incl. GST", type: "boolean", section: "Tax (confirm with your CA)", width: "third" },
    { name: "tax.invoicePrefix", label: "Invoice prefix", type: "text", section: "Tax (confirm with your CA)", width: "third" },

    { name: "booking.holdMinutes", label: "Checkout hold (minutes)", type: "number", section: "Booking rules", width: "third" },
    { name: "booking.maxAdvanceDays", label: "Bookable days ahead", type: "number", section: "Booking rules", width: "third" },
    { name: "booking.defaultMinGroupSize", label: "Default Darshan min group", type: "number", section: "Booking rules", width: "third" },
    { name: "booking.defaultAdvanceDays", label: "Default Darshan advance days", type: "number", section: "Booking rules", width: "third" },
    { name: "booking.defaultMealMinNights", label: "Default meal min nights", type: "number", section: "Booking rules", width: "third" },

    { name: "notifications.adminWhatsappNumbers", label: "VHI WhatsApp numbers (E.164)", type: "tags", section: "Notifications", help: "e.g. +919876543210" },
    { name: "notifications.adminEmails", label: "VHI notification emails", type: "tags", section: "Notifications" },
    { name: "notifications.sendGuestWhatsapp", label: "WhatsApp confirmation to guest", type: "boolean", section: "Notifications", width: "half" },
    { name: "notifications.sendGuestEmail", label: "Email confirmation to guest", type: "boolean", section: "Notifications", width: "half" },
    { name: "notifications.templateLanguage", label: "Template language", type: "text", section: "Notifications", width: "third" },
    { name: "notifications.adminBookingTemplate", label: "Admin booking template", type: "text", section: "Notifications", width: "third" },
    { name: "notifications.guestConfirmationTemplate", label: "Guest confirmation template", type: "text", section: "Notifications", width: "third" },
    { name: "notifications.adminEnquiryTemplate", label: "Admin enquiry template", type: "text", section: "Notifications", width: "half" },
    { name: "notifications.guestCancellationTemplate", label: "Guest cancellation template", type: "text", section: "Notifications", width: "half" },

    { name: "contacts", label: "Reliable drivers & services", type: "list", section: "Local contacts", fields: [{ name: "name", label: "Name", type: "text" }, { name: "role", label: "Service", type: "text" }, { name: "phone", label: "Phone", type: "text" }, { name: "showToGuests", label: "Share with guests", type: "boolean" }] },

    { name: "seo.defaultTitle", label: "Default SEO title", type: "text", section: "SEO", width: "full" },
    { name: "seo.defaultDescription", label: "Default SEO description", type: "textarea", section: "SEO", width: "full" },
    { name: "seo.ogImage", label: "Default share image", type: "image", folder: "brand", section: "SEO" },
  ],
};

export const RESOURCE_MAP: Record<string, ResourceConfig> = Object.fromEntries([...RESOURCES, SETTINGS_RESOURCE].map((r) => [r.key, r]));
export const getResource = (key: string) => RESOURCE_MAP[key];
